# Production build pipeline preparing for npm publish

trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:

- script: git checkout main
- task: CopyFiles@2
  displayName: 'Copy Files to staging directory'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: |
     **/*
     !spec/**
     !.azure-pipelines/**
     !.github/**
     !.git/**
     !.vscode/**
     !typings-demo.gif
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
